- name: Add Dagster chart repo
  community.kubernetes.helm_repository:
    name: dagster
    repo_url: "{{ helm_url }}"

- name: Deploy Dagster chart
  community.kubernetes.helm:
    name: dagster
    chart_ref: "{{ chart_ref }}"
    chart_version: "{{ chart_version }}"
    create_namespace: true
    release_namespace: "{{ namespace }}"
    values: "{{ lookup('template', config_file) | from_yaml }}"
    kubeconfig: "{{ kubeconfig }}"

- name: Get encoded user:password pair
  shell: "set -o pipefail && htpasswd -nb {{ user_name }} {{ user_password }} | openssl base64"
  register: passwd
  delegate_to: 127.0.0.1
  changed_when: false

- name: Set password
  set_fact:
    passwd: "{{ passwd.stdout }}"

- name: Copy Traefik CRD file to machine
  template:
    src: "{{ traefik_crd_file }}"
    dest: traefik_crd.yaml
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Install Traefik CRD
  community.kubernetes.k8s:
    state: present
    src: traefik_crd.yaml
    kubeconfig: "{{ kubeconfig }}"

- name: Create the Dagster secret
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', secret_file) | from_yaml_all }}"
    validate:
      fail_on_error: true
    kubeconfig: "{{ kubeconfig }}"

- name: Copy ingress file to machine
  template:
    src: "{{ ingress_file }}"
    dest: dagster_ingress.yaml
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Create the ingress
  community.kubernetes.k8s:
    state: present
    src: dagster_ingress.yaml
    kubeconfig: "{{ kubeconfig }}"

- name: Create the Dagster configmap
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', configmap_file) | from_yaml_all }}"
    validate:
      fail_on_error: true
    kubeconfig: "{{ kubeconfig }}"
