- name: Add Dagster chart repo
  community.kubernetes.helm_repository:
    name: dagster
    repo_url: "{{ helm_url }}"

- name: Deploy Dagster chart
  community.kubernetes.helm:
    name: dagster
    chart_ref: "{{ chart_ref }}"
    chart_version: "{{ chart_version }}"
    create_namespace: true
    release_namespace: "{{ namespace }}"
    values: "{{ lookup('template', config_file) | from_yaml }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Copy ingress file to machine
  template:
    src: "{{ ingress_file }}"
    dest: dagser_ingress.yaml
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Create the ingress
  community.kubernetes.k8s:
    state: present
    src: dagser_ingress.yaml
    kubeconfig: /etc/rancher/k3s/k3s.yaml
