repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.0.7
    hooks:
      - id: ansible-lint
        description: This hook runs ansible-lint.
        entry: ansible-lint --force-color
        files: \.(yaml|yml)$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
