---
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true

- name: ZSH facts
  shell: 'echo $SHELL'
  register: default_shell
  changed_when: false

- name: Make zsh default
  command: chsh -s /bin/zsh
  when: default_shell.stdout.find('/bin/zsh') == -1
