---
- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: true

- name: Install snap packages
  block:
    - name: Install Go snap on Ubuntu
      snap:
        name: "{{ item.package }}"
        state: present
        classic: true
        channel: "{{ item.channel }}"
      with_items: "{{ snap_packages }}"

- name: ZSH facts
  shell: 'echo $SHELL'
  register: default_shell
  changed_when: false

- name: Make zsh default
  command: chsh -s /bin/zsh
  when: default_shell.stdout.find('/bin/zsh') == -1
