global:
  name: consul
  datacenter: dc1
client:
  enabled: true
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    maxUnavailable: 0
ui:
  enabled: true
connectInject:
  enabled: true
controller:
  enabled: true
