---
- name: Deploy validation services
  block:
    - name: Create the whoami deployment
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('template', whoami_manifest) | from_yaml_all }}"
        validate:
          fail_on_error: false
          strict: true

    - name: Create the echo deployment
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('template', echo_manifest) | from_yaml_all }}"
        validate:
          fail_on_error: false
          strict: true

    - name: Create the Nginx deployment
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('template', nginx_manifest) | from_yaml_all }}"
        validate:
          fail_on_error: false
          strict: true

  delegate_to: 127.0.0.1

- name: "Wait for echo to come up"
  uri:
    url: "{{ echo_url }}"
    return_content: true
  register: result
  until: "'echo-one' in result.content"
  retries: 10
  delay: 1

- name: "Wait for whoami to come up"
  uri:
    url: "{{ whoami_url }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
