---
apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: external-connectivity
  namespace: redpanda
spec:
  image: vectorized/redpanda
  version: latest
  replicas: 2
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
      - port: 9092
      - external:
          enabled: true
          # subdomain: kafka.jitsejan.com
    pandaproxyApi:
      - port: 8082
      - external:
          enabled: true
          # subdomain: kafka.jitsejan.com
    adminApi:
      - port: 9644
    developerMode: true
---
