dev:
  hosts:
    local:
      ansible_connection: local
      ansible_python_interpreter: "/usr/local/Cellar/ansible/3.3.0/libexec/bin/python3.9"
prod:
  hosts:
    databox:
      ansible_host: databox.jitsejan.com
      ansible_user: root
