dev:
  hosts:
    local:
      ansible_connection: local
      ansible_python_interpreter: "/usr/local/Cellar/ansible/3.3.0/libexec/bin/python3.9"
prod:
  hosts:
    node01:
      ansible_host: 63.250.53.137
      ansible_user: root
    node02:
      ansible_host: 89.233.107.140
      ansible_user: root
master:
  hosts:
    node01:
      ansible_host: 63.250.53.137
      ansible_user: root
